// // Mocks generated by Mockito 5.4.4 from annotations
// // in news_app/test/data/repositories/api_repo_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;

// import 'package:chopper/chopper.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:news_app/network/model_response.dart' as _i5;
// import 'package:news_app/network/query_result.dart' as _i6;
// import 'package:news_app/network/service_interface.dart' as _i3;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeResponse_0<BodyType> extends _i1.SmartFake
//     implements _i2.Response<BodyType> {
//   _FakeResponse_0(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// /// A class which mocks [ServiceInterface].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockServiceInterface extends _i1.Mock implements _i3.ServiceInterface {
//   @override
//   _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>> queryEverything({
//     String? q,
//     String? sources,
//     String? domains,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#queryEverything, [], {
//               #q: q,
//               #sources: sources,
//               #domains: domains,
//             }),
//             returnValue:
//                 _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>.value(
//                   _FakeResponse_0<_i5.Result<_i6.QueryResult>>(
//                     this,
//                     Invocation.method(#queryEverything, [], {
//                       #q: q,
//                       #sources: sources,
//                       #domains: domains,
//                     }),
//                   ),
//                 ),
//             returnValueForMissingStub:
//                 _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>.value(
//                   _FakeResponse_0<_i5.Result<_i6.QueryResult>>(
//                     this,
//                     Invocation.method(#queryEverything, [], {
//                       #q: q,
//                       #sources: sources,
//                       #domains: domains,
//                     }),
//                   ),
//                 ),
//           )
//           as _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>);

//   @override
//   _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>> topHeadlines({
//     String? country,
//     String? category,
//     String? sources,
//     int? pageSize,
//     int? page,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#topHeadlines, [], {
//               #country: country,
//               #category: category,
//               #sources: sources,
//               #pageSize: pageSize,
//               #page: page,
//             }),
//             returnValue:
//                 _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>.value(
//                   _FakeResponse_0<_i5.Result<_i6.QueryResult>>(
//                     this,
//                     Invocation.method(#topHeadlines, [], {
//                       #country: country,
//                       #category: category,
//                       #sources: sources,
//                       #pageSize: pageSize,
//                       #page: page,
//                     }),
//                   ),
//                 ),
//             returnValueForMissingStub:
//                 _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>.value(
//                   _FakeResponse_0<_i5.Result<_i6.QueryResult>>(
//                     this,
//                     Invocation.method(#topHeadlines, [], {
//                       #country: country,
//                       #category: category,
//                       #sources: sources,
//                       #pageSize: pageSize,
//                       #page: page,
//                     }),
//                   ),
//                 ),
//           )
//           as _i4.Future<_i2.Response<_i5.Result<_i6.QueryResult>>>);

//   @override
//   _i4.Future<_i2.Response<_i5.Result<_i3.QuerySource>>> sources() =>
//       (super.noSuchMethod(
//             Invocation.method(#sources, []),
//             returnValue:
//                 _i4.Future<_i2.Response<_i5.Result<_i3.QuerySource>>>.value(
//                   _FakeResponse_0<_i5.Result<_i3.QuerySource>>(
//                     this,
//                     Invocation.method(#sources, []),
//                   ),
//                 ),
//             returnValueForMissingStub:
//                 _i4.Future<_i2.Response<_i5.Result<_i3.QuerySource>>>.value(
//                   _FakeResponse_0<_i5.Result<_i3.QuerySource>>(
//                     this,
//                     Invocation.method(#sources, []),
//                   ),
//                 ),
//           )
//           as _i4.Future<_i2.Response<_i5.Result<_i3.QuerySource>>>);
// }
