// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofK4rEZsUBSIqFe4B4n1S48wWV77b_b4',
    appId: '1:443933798581:web:91a0e12a55093fe8e68efc',
    messagingSenderId: '443933798581',
    projectId: 'newsapp-66cb9',
    authDomain: 'newsapp-66cb9.firebaseapp.com',
    storageBucket: 'newsapp-66cb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMC7Aq0eG9p1db0jq2966X3nEFVck4D-A',
    appId: '1:443933798581:android:61b7f7936fa4abfee68efc',
    messagingSenderId: '443933798581',
    projectId: 'newsapp-66cb9',
    storageBucket: 'newsapp-66cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsv26P5jpvLtqBBd5Jg7CCV2JOqUCxLA',
    appId: '1:443933798581:ios:dd329963cfb4ab57e68efc',
    messagingSenderId: '443933798581',
    projectId: 'newsapp-66cb9',
    storageBucket: 'newsapp-66cb9.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxsv26P5jpvLtqBBd5Jg7CCV2JOqUCxLA',
    appId: '1:443933798581:ios:dd329963cfb4ab57e68efc',
    messagingSenderId: '443933798581',
    projectId: 'newsapp-66cb9',
    storageBucket: 'newsapp-66cb9.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofK4rEZsUBSIqFe4B4n1S48wWV77b_b4',
    appId: '1:443933798581:web:03aedba2e58746e8e68efc',
    messagingSenderId: '443933798581',
    projectId: 'newsapp-66cb9',
    authDomain: 'newsapp-66cb9.firebaseapp.com',
    storageBucket: 'newsapp-66cb9.firebasestorage.app',
  );
}
